### create project

post http://localhost:3000/project/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthdmVoIiwiaWF0IjoxNjUxMzQyNTIxLCJleHAiOjE2ODI4Nzg1MjF9.VOSDYmsErnqGXsAQ3s5q_W87oOoYp_QxnzUXTU18iLw
Content-Type: application/json

{
  "title" : "title of new project",
  "text" : "text of new project for project manager with nodejs",
  "tags" : [
    "tag1", "tag2", "tag3"
  ]
}

### get all project
Get http://localhost:3000/project/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthdmVoIiwiaWF0IjoxNjUxMzQyNTIxLCJleHAiOjE2ODI4Nzg1MjF9.VOSDYmsErnqGXsAQ3s5q_W87oOoYp_QxnzUXTU18iLw
Content-Type: application/json

### get project by ID
Get http://localhost:3000/project/6272a7fb773dd4e5f751333e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthdmVoIiwiaWF0IjoxNjUxMzQyNTIxLCJleHAiOjE2ODI4Nzg1MjF9.VOSDYmsErnqGXsAQ3s5q_W87oOoYp_QxnzUXTU18iLw
Content-Type: application/json

### remove project by ID
Delete http://localhost:3000/project/remove/6272a731095a4da7b696ff26
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthdmVoIiwiaWF0IjoxNjUxMzQyNTIxLCJleHAiOjE2ODI4Nzg1MjF9.VOSDYmsErnqGXsAQ3s5q_W87oOoYp_QxnzUXTU18iLw
Content-Type: application/json

### edit project by ID
Put http://localhost:3000/project/edit/6272a7fb773dd4e5f751333e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthdmVoIiwiaWF0IjoxNjUxMzQyNTIxLCJleHAiOjE2ODI4Nzg1MjF9.VOSDYmsErnqGXsAQ3s5q_W87oOoYp_QxnzUXTU18iLw
Content-Type: application/json

{
  "title" : "new title for test",
  "text" : "new tet for test updating project",
  "tags" : [
    "tag1", " ", "", 0
  ],
  "text2" : "dddd"
}

