### create project

post http://localhost:3000/project/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthdmVoIiwiaWF0IjoxNjUxMzQyNTIxLCJleHAiOjE2ODI4Nzg1MjF9.VOSDYmsErnqGXsAQ3s5q_W87oOoYp_QxnzUXTU18iLw
Content-Type: application/json

{
  "title" : "title of new project",
  "text" : "text of new project for project manager with nodejs",
  "tags" : [
    "tag1", "tag2", "tag3"
  ]
}